# User Configuration for ${keyboard.name}

CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Mouse Emulation Behaviors
CONFIG_ZMK_POINTING=y

# Soft Off Behavior
CONFIG_ZMK_PM_SOFT_OFF=y

# DISPLAY
# CONFIG_ZMK_DISPLAY=y

# Battery reporting for both sides
CONFIG_BT_BAS=y
CONFIG_ZMK_BATTERY_REPORTING=y

# For split keyboards:
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
